StudentRecordBN/Controllers/GradesScaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentRecordBN.Models;

namespace StudentRecordBN.Controllers
{
   
    public class GradesScaffController : Controller
    {
        private readonly AppDBContext _context;

        public GradesScaffController(AppDBContext context)
        {
            _context = context;
        }

        // GET: GradesScaff
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Grades.Include(g => g.Student);
            return View(await appDBContext.ToListAsync());
        }

        // GET: GradesScaff/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades
                .Include(g => g.Student)
                .FirstOrDefaultAsync(m => m.GradeId == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // GET: GradesScaff/Create
      
        public IActionResult Create()
        {
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "StudentId");
            return View();
        }

        // POST: GradesScaff/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("GradeId,Subject,Value,StudentId")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grade);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "StudentId", grade.StudentId);
            return View(grade);
        }

        // GET: GradesScaff/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades.FindAsync(id);
            if (grade == null)
            {
                return NotFound();
            }
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "StudentId", grade.StudentId);
            return View(grade);
        }

        // POST: GradesScaff/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("GradeId,Subject,Value,StudentId")] Grade grade)
        {
            if (id != grade.GradeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GradeExists(grade.GradeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "StudentId", grade.StudentId);
            return View(grade);
        }

        // GET: GradesScaff/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades
                .Include(g => g.Student)
                .FirstOrDefaultAsync(m => m.GradeId == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: GradesScaff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grade = await _context.Grades.FindAsync(id);
            _context.Grades.Remove(grade);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GradeExists(int id)
        {
            return _context.Grades.Any(e => e.GradeId == id);
        }
    }
}

StudentRecordBN/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentRecordBN.Models;

namespace StudentRecordBN.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        
        public IActionResult About()
        {
            ViewData["Message"] = "Our application starts here";

            return View();
        }
        
        public IActionResult Contact()
        {
            ViewData["Message"] = "Contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentRecordBN/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<html>
      <body>
            <img src="~/images/testare.jpg" width="1200" height="500" alt="Students" >
      </body>
 </html>


<p>This application is designed for simplifying the management of students and assingments.</p>

StudentRecordBN/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Str.Tineretului<br />
    Balea Nicusor Robert srl.<br />
    <abbr title="Phone">P:</abbr>
    0742212665
</address>

<address>
    <strong>Support:</strong> <a href=BaleaInc@st-record.com">BaleaInc@st-record.com</a><br />
    <strong>Marketing:</strong> <a href="BaleaInc@st-record.com">BaleaInc@st-record.com</a>
</address>

StudentRecordBN/Views/Home/Index.cshtml
<style>
    



    .button {
        border-radius: 4px;
        background-color: rgba(6, 1, 4, 0.69);
        border: none;
        color: #ffffff;
        text-align: center;
        font-size: 28px;
        padding: 20px;
        width: 300px;
        height: 100px;
        transition: all 0.5s;
        cursor: pointer;
        margin: 5px;
    }

    .button span {
        cursor: pointer;
        display: inline-block;
        position: relative;
        transition: 1s;
        margin-left: auto;
        margin-right: auto;
    }

        .button span:after {
            content: '\00bb';
            position: absolute;
            opacity: 0;
            top: 0;
            right: -20px;
            transition: 0.5s;
        }

    .button:hover span {
        padding-right: 25px;
    }

        .button:hover span:after {
            opacity: 1;
            right: 0;
        }

</style>
<h1>
    <a asp-action="Index" asp-controller="GradesScaff"> <button class="button btn btn-black"><span>ViewGrades</span></button></a>
    <a asp-action="Index" asp-controller="Students"> <button class="button btn btn-black"><span>StudentManagement</span></button></a>


</h1>

<div>

    <img src="~/images/study.jpg" width="1200" height="500" alt="Poza">


</div>

StudentRecordBN/Views/Home/View.cshtml
@model StudentRecordBN.Models.Grade
@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<div>
    <a asp-action="Index" asp-controller = "GradesScaff">Index</a>  
    
</div>